# Generated by Django 5.2 on 2025-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_socio_delete_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
